// GENERATED by tools/gen_link_vectors_mc.py from
// contracts/vectors/link_frames.json. Do not edit by hand.
//
// Copyright (C) 2026 Michael Van Geertruy. GPL-3.0-or-later; see LICENSE.

import Toybox.Lang;

module LinkVectors {
    const CONTRACT_VERSION = "0.1";
    const LINK_VERSION = "0.1";
    const UUID_BASE = "8ac687f5-a08b-4851-b89f-e6b39081268e";
    const UUID_SERVICE = "8ac60001-a08b-4851-b89f-e6b39081268e";
    const UUID_CONTROL = "8ac60002-a08b-4851-b89f-e6b39081268e";
    const UUID_STATUS = "8ac60003-a08b-4851-b89f-e6b39081268e";
    const UUID_DATA = "8ac60004-a08b-4851-b89f-e6b39081268e";
    const UUID_PROBE = "8ac600f0-a08b-4851-b89f-e6b39081268e";
    const MAXFRAME = 20;
    const STATUSSIZE = 18;
    const LINKVERSIONBYTE = 1;
    const SERVERMAJOR = 0;
    const SERVERMINOR = 1;
    const OPS_HELLO = 1;
    const OPS_PING = 2;
    const OPS_COMMAND = 3;
    const OPS_GET_CHANGED = 4;
    const OPS_GET_TEXT = 5;
    const OPS_TESTRANGEFIRST = 240;
    const OPS_TESTRANGELAST = 254;
    const OPS_RX_MARK = 241;
    const FRAMETYPES_HELLO_ACK = 129;
    const FRAMETYPES_ACK = 130;
    const FRAMETYPES_RESULT = 131;
    const FRAMETYPES_EVENT_SUMMARY = 132;
    const FRAMETYPES_END = 133;
    const FRAMETYPES_TEXT = 134;
    const FRAMETYPES_ERROR = 143;
    const LINKSTATUS_OK = 0;
    const LINKSTATUS_UNKNOWNOP = 1;
    const LINKSTATUS_BADLENGTH = 2;
    const LINKSTATUS_VERSIONMISMATCH = 3;
    const LINKSTATUS_BUSY = 4;
    const STATUSFLAGS_MONITORING = 1;
    const STATUSFLAGS_EARLYWARNINGENABLED = 2;
    const STATUSFLAGS_EARLYWARNINGRESTING = 4;
    const STATUSFLAGS_ALERTPENDING = 8;
    const STATUSFLAGS_SLEEPMODE = 16;
    const SCHEDULE_SIMULTANEOUS = 0;
    const SCHEDULE_RECON = 1;
    const SCHEDULE_REPORT = 2;
    const CAPABILITIES_LOCALWIFIMONITOR = 1;
    const CAPABILITIES_LOCALBLEMONITOR = 2;
    const CAPABILITIES_DISPLAY = 4;
    const CAPABILITIES_LED = 8;
    const CAPABILITIES_BUTTON = 16;
    const PROBE_SIZES = [20, 21, 64, 180] as Array<Number>;

    const STATUS = [
        {:name => "increment1_nominal", :bytes => [0x01, 0xA2, 0x3F, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2A, 0x00, 0x00]b, :fields => {:linkVersion => 1, :sessionId => 16290, :changeSeq => 7, :flags => 0, :selected => 0, :active => 0, :eventCount => 0, :lastAlertEventId => 0, :heartbeat => 42, :schedule => 0, :nextReportS => 0}},
        {:name => "all_zero_except_version", :bytes => [0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]b, :fields => {:linkVersion => 1, :sessionId => 0, :changeSeq => 0, :flags => 0, :selected => 0, :active => 0, :eventCount => 0, :lastAlertEventId => 0, :heartbeat => 0, :schedule => 0, :nextReportS => 0}},
        {:name => "max_values", :bytes => [0x01, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x1F, 0x11, 0x11, 0x28, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x02, 0xFF]b, :fields => {:linkVersion => 1, :sessionId => 65535, :changeSeq => 4294967295l, :flags => 31, :selected => 17, :active => 17, :eventCount => 40, :lastAlertEventId => 4294967295l, :heartbeat => 255, :schedule => 2, :nextReportS => 255}},
        {:name => "heartbeat_wrap_and_flags", :bytes => [0x01, 0x02, 0x01, 0x04, 0x03, 0x02, 0x01, 0x0A, 0x05, 0x05, 0x03, 0x21, 0x00, 0x00, 0x00, 0x00, 0x01, 0x3C]b, :fields => {:linkVersion => 1, :sessionId => 258, :changeSeq => 16909060, :flags => 10, :selected => 5, :active => 5, :eventCount => 3, :lastAlertEventId => 33, :heartbeat => 0, :schedule => 1, :nextReportS => 60}},
    ] as Array<Dictionary>;

    const REQUESTS = [
        {:name => "hello", :op => "HELLO", :bytes => [0x01, 0x11, 0x00, 0x01]b, :fields => {:reqId => 17, :clientMajor => 0, :clientMinor => 1}},
        {:name => "hello_newer_minor", :op => "HELLO", :bytes => [0x01, 0x12, 0x00, 0x09]b, :fields => {:reqId => 18, :clientMajor => 0, :clientMinor => 9}},
        {:name => "ping", :op => "PING", :bytes => [0x02, 0x21, 0xEF, 0xBE, 0xAD, 0xDE]b, :fields => {:reqId => 33, :token => 3735928559l}},
        {:name => "ping_zero_token", :op => "PING", :bytes => [0x02, 0x00, 0x00, 0x00, 0x00, 0x00]b, :fields => {:reqId => 0, :token => 0}},
    ] as Array<Dictionary>;

    const REPLIES = [
        {:name => "hello_ack_ok", :type => "HELLO_ACK", :bytes => [0x81, 0x11, 0x00, 0x00, 0x01, 0xA2, 0x3F, 0x1E, 0x00, 0x14]b, :fields => {:reqId => 17, :linkStatus => 0, :serverMajor => 0, :serverMinor => 1, :sessionId => 16290, :capabilities => 30, :maxFrame => 20}},
        {:name => "hello_ack_version_mismatch", :type => "HELLO_ACK", :bytes => [0x81, 0x13, 0x03, 0x00, 0x01, 0xA2, 0x3F, 0x1E, 0x00, 0x14]b, :fields => {:reqId => 19, :linkStatus => 3, :serverMajor => 0, :serverMinor => 1, :sessionId => 16290, :capabilities => 30, :maxFrame => 20}},
        {:name => "ack", :type => "ACK", :bytes => [0x82, 0x21, 0x00, 0xEF, 0xBE, 0xAD, 0xDE, 0x2A]b, :fields => {:reqId => 33, :linkStatus => 0, :token => 3735928559l, :heartbeat => 42}},
        {:name => "error_unknown_op", :type => "ERROR", :bytes => [0x8F, 0x05, 0x01]b, :fields => {:reqId => 5, :linkStatus => 1}},
        {:name => "error_bad_length", :type => "ERROR", :bytes => [0x8F, 0x21, 0x02]b, :fields => {:reqId => 33, :linkStatus => 2}},
    ] as Array<Dictionary>;

}
