#!/usr/bin/env python3
# LayerTime - passive early-warning system.
#
# Copyright (C) 2026 Michael Van Geertruy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Render the LayerTime owl for the T-Dongle-C5 status LCD.

The T-Ultra draws the owl from the SVG embedded in
src/platform/twatch_ultra/ui/OwlLogo.cpp through LVGL's vector engine. The
C5's 160 x 80 ST7735 does not justify the vector engine, so this script
rasterises the same SVG, once, into a 56 x 56 RGB565 bitmap and writes it as
src/platform/tdongle_c5/C5OwlImage.cpp. The SVG in OwlLogo.cpp stays the
single source of the artwork; rerun this script whenever it changes.

    python3 tools/c5_owl_image.py

Requires Pillow. Every path in the SVG is a closed polygon (M, L, Z only),
so no general SVG renderer is needed: the polygons are drawn 8x oversampled
on black and downsampled with a Lanczos filter for anti-aliased edges.
"""

import pathlib
import re
import struct

from PIL import Image, ImageDraw

ROOT = pathlib.Path(__file__).resolve().parent.parent
SVG_SOURCE = ROOT / "src/platform/twatch_ultra/ui/OwlLogo.cpp"
OUTPUT = ROOT / "src/platform/tdongle_c5/C5OwlImage.cpp"

SIZE = 56          # pixels, square
OVERSAMPLE = 8
PAD = 1            # pixels of black around the artwork
LV_IMAGE_HEADER_MAGIC = 0x19
LV_COLOR_FORMAT_RGB565 = 0x12


def load_polygons():
    text = SVG_SOURCE.read_text(encoding="utf-8")
    paths = re.findall(r'<path fill="(#[0-9A-Fa-f]{6})" fill-rule="evenodd" d="([^"]+)"/>', text)
    if not paths:
        raise SystemExit(f"no <path> elements found in {SVG_SOURCE}")
    polygons = []
    for colour, d in paths:
        if re.search(r"[^MLZmlz0-9.\s-]", d):
            raise SystemExit("OwlLogo.cpp now uses SVG commands other than M/L/Z; extend this script")
        numbers = [float(n) for n in re.findall(r"-?\d+(?:\.\d+)?", d)]
        polygons.append((colour, list(zip(numbers[0::2], numbers[1::2]))))
    return polygons


def render(polygons):
    xs = [x for _, pts in polygons for x, _ in pts]
    ys = [y for _, pts in polygons for _, y in pts]
    x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
    big = SIZE * OVERSAMPLE
    scale = (SIZE - 2 * PAD) * OVERSAMPLE / max(x1 - x0, y1 - y0)
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    image = Image.new("RGB", (big, big), (0, 0, 0))
    draw = ImageDraw.Draw(image)
    for colour, pts in polygons:
        draw.polygon([((x - cx) * scale + big / 2, (y - cy) * scale + big / 2) for x, y in pts], fill=colour)
    return image.resize((SIZE, SIZE), Image.LANCZOS)


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def write_source(image):
    pixels = image.load()
    words = [rgb565(*pixels[x, y]) for y in range(SIZE) for x in range(SIZE)]
    data = b"".join(struct.pack("<H", w) for w in words)  # LVGL native little-endian RGB565
    rows = []
    for i in range(0, len(data), 24):
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 24]) + ",")
    body = "\n".join(rows)
    OUTPUT.write_text(f"""// LayerTime - passive early-warning firmware for the LILYGO T-Dongle-C5.
//
// Copyright (C) 2026 Michael Van Geertruy
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// GENERATED by tools/c5_owl_image.py from the SVG in
// src/platform/twatch_ultra/ui/OwlLogo.cpp. Do not edit by hand; rerun the
// script when the owl changes. {SIZE} x {SIZE}, RGB565, LVGL native byte order,
// on a black background.

#if defined(LAYERTIME_TARGET_TDONGLE_C5)

#include "C5OwlImage.h"

namespace layertime {{
namespace tdongle_c5 {{

namespace {{

const uint8_t kOwlPixels[{len(data)}] = {{
{body}
}};

}} // namespace

const lv_image_dsc_t kOwlImage = {{
    {{
        LV_IMAGE_HEADER_MAGIC,   // magic
        LV_COLOR_FORMAT_RGB565,  // cf
        0,                       // flags
        {SIZE},                      // w
        {SIZE},                      // h
        {SIZE * 2},                     // stride, bytes per row
        0,                       // reserved_2
    }},
    sizeof(kOwlPixels),
    kOwlPixels,
    nullptr,
    nullptr,
}};

}} // namespace tdongle_c5
}} // namespace layertime

#endif
""", encoding="utf-8", newline="\r\n")
    return len(data)


if __name__ == "__main__":
    size = write_source(render(load_polygons()))
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {SIZE}x{SIZE} RGB565, {size} bytes")
