#!/usr/bin/env python3
# LayerTime - passive early-warning system.
#
# Copyright (C) 2026 Michael Van Geertruy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Generate garmin/source/link/LinkVectors.mc from contracts/vectors/link_frames.json.

Monkey C cannot read a JSON file from the repository at run time, so the
LayerTime Link vectors are compiled into the Connect IQ app as constants.
The C++ suite reads the JSON directly; test/test_link_vectors_mc/ checks that
the generated file is what this script produces, so the two bindings are
always tested against the same bytes.

    python3 tools/gen_link_vectors_mc.py            # writes the file
    python3 tools/gen_link_vectors_mc.py --check    # exit 1 if it is stale
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "contracts/vectors/link_frames.json"
OUTPUT = ROOT / "garmin/source/link/LinkVectors.mc"


def byte_array(hexstr):
    if not hexstr:
        return "[]b"
    return "[" + ", ".join(f"0x{hexstr[i:i + 2]}" for i in range(0, len(hexstr), 2)) + "]b"


def number(v):
    # Values above the 32-bit signed range need a Long literal in Monkey C.
    return f"{v}l" if v > 0x7FFFFFFF else str(v)


def render(vectors):
    c = vectors["constants"]
    out = []
    out.append("// GENERATED by tools/gen_link_vectors_mc.py from")
    out.append("// contracts/vectors/link_frames.json. Do not edit by hand.")
    out.append("//")
    out.append("// Copyright (C) 2026 Michael Van Geertruy. GPL-3.0-or-later; see LICENSE.")
    out.append("")
    out.append("import Toybox.Lang;")
    out.append("")
    out.append("module LinkVectors {")
    out.append(f'    const CONTRACT_VERSION = "{vectors["contractVersion"]}";')
    out.append(f'    const LINK_VERSION = "{vectors["linkVersion"]}";')
    for k, v in vectors["uuids"].items():
        out.append(f'    const UUID_{k.upper()} = "{v}";')
    for k in ("maxFrame", "statusSize", "linkVersionByte", "serverMajor", "serverMinor"):
        out.append(f"    const {k.upper()} = {c[k]};")
    for group in ("ops", "frameTypes", "linkStatus", "statusFlags", "schedule", "capabilities"):
        for k, v in c[group].items():
            out.append(f"    const {group.upper()}_{k.upper()} = {v};")
    out.append("    const PROBE_SIZES = [" + ", ".join(str(s) for s in c["probeSizes"]) + "] as Array<Number>;")
    out.append("")

    def dict_lines(name, entries, field_keys, extra):
        out.append(f"    const {name} = [")
        for e in entries:
            parts = [f':name => "{e["name"]}"']
            for k, v in extra(e):
                parts.append(f":{k} => {v}")
            fields = ", ".join(f":{k} => {number(e['fields'][k])}" for k in field_keys if k in e["fields"])
            parts.append(f":fields => {{{fields}}}")
            out.append("        {" + ", ".join(parts) + "},")
        out.append("    ] as Array<Dictionary>;")
        out.append("")

    status_keys = ["linkVersion", "sessionId", "changeSeq", "flags", "selected", "active", "eventCount",
                   "lastAlertEventId", "heartbeat", "schedule", "nextReportS"]
    dict_lines("STATUS", vectors["status"], status_keys, lambda e: [("bytes", byte_array(e["bytes"]))])
    dict_lines("REQUESTS", vectors["requests"],
               ["reqId", "clientMajor", "clientMinor", "token"],
               lambda e: [("op", f'"{e["op"]}"'), ("bytes", byte_array(e["bytes"]))])
    dict_lines("REPLIES", vectors["replies"],
               ["reqId", "linkStatus", "serverMajor", "serverMinor", "sessionId", "capabilities", "maxFrame",
                "token", "heartbeat"],
               lambda e: [("type", f'"{e["type"]}"'), ("bytes", byte_array(e["bytes"]))])
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    vectors = json.loads(SOURCE.read_text(encoding="utf-8"))
    text = render(vectors)
    if "--check" in sys.argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print(f"stale: {OUTPUT.relative_to(ROOT)} does not match {SOURCE.relative_to(ROOT)}")
            return 1
        print("up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    # The repository keeps CRLF line endings; --check ignores the difference.
    OUTPUT.write_text(text, encoding="utf-8", newline="\r\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
